version: "3.9"  # optional since v1.27.0
services:
  redis:
    image: redis:7.0.5
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - ./redisdata:/data
    deploy:
      resources:
        limits:
          memory: 1G